# Generated by Django 3.2.9 on 2021-12-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('vendas', '0002_auto_20211214_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItensVendas',
            new_name='ItemsVenda',
        ),
    ]
