# Generated by Django 3.2.9 on 2021-12-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_rename_itensvendas_itemsvenda'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsvenda',
            options={'verbose_name_plural': 'Itens do pedido'},
        ),
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('AB', 'Aberta'), ('FE', 'Fechada'), ('PR', 'Processando'), ('DC', 'Desconhecido')], default='DC', max_length=7),
        ),
    ]
