# Generated by Django 3.2.9 on 2021-12-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('vendas', '0004_auto_20211228_2117'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemsvenda',
            unique_together={('venda', 'produto')},
        ),
    ]
