# Generated by Django 3.2.9 on 2021-12-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_auto_20211213_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='ItensVendas',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
