# Generated by Django 3.2.9 on 2021-12-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20211213_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('deletar_clientes', 'Deletar clientes'),)},
        ),
    ]
